AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: MXNet Lambda Function
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      MemorySize: 1536
      Timeout: 60
      CodeUri: src/lambda_function.zip
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /predict
            Method: get

Outputs:
  ApiUrl:
    Description: "API endpoint URL for Prod environment"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
